name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # 빌드 명령어 (예: React 프로젝트에서는 `npm run build`)

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v1.2.0 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.SSH_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          # script: | # 실행할 스크립트
          #   cd /home/ubuntu/Server-V2
          #   git pull origin dev
          #   pm2 kill
          #   npm i --force
          #   npm run build
          #   pm2 start dist/main.js

      - name: Deploy to EC2
        run: |
          scp -r ./dist ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}:/home/ubuntu/projects/nestjs