name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm build  # 빌드 명령어 (예: React 프로젝트에서는 `npm run build`)

      - name: Deploy to server
        run: |
          scp -r ./build ubuntu@ec2-43-200-118-236.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/projects/nestjs
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
